name: Process Docstrings

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.x  # Specify the Julia version you want to use

      - name: Install dependencies
        run: julia -e 'using Pkg; Pkg.instantiate()'

      - name: Process Docstrings
        run: julia --project=docs/ docs/make.jl
